name: 'Branch Cleanup Bot'
description: 'Delete branches with no recent activity'
author: 'enaumchuk'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  stale_days:
    description: 'Number of days since last commit before a branch is considered stale'
    required: false
    default: '90'
  skip_unmerged:
    description: 'Skip branches that have unmerged commits'
    required: false
    default: 'true'
  skip_open_prs:
    description: 'Skip branches with open pull requests'
    required: false
    default: 'true'
  skip_branches:
    description: 'Comma-separated list of branches excluded from processing (supports wildcards like release/*)'
    required: false
    default: 'main,master,develop,development,staging,production,keep-alive-*'
  max_branches_to_delete:
    description: 'Max number of branches to delete in a single run'
    required: false
    default: '1000'
  process_throttle_ms:
    description: 'Milliseconds to wait between processing each branch'
    required: false
    default: '0'
  rate_limit_threshold:
    description: "The action will stop if the remaining GitHub API rate limit falls below this value"
    required: false
    default: '100''
  continue_on_errors:
    description: 'Continue processing other branches if an error occurs with one'
    required: false
    default: 'false'
  dry_run:
    description: 'Run in dry-run mode without deleting branches'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'